[package]
name = "urza-mulligan"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
urza-cards = { path = "../urza-cards" }
urza-core = { path = "../urza-core" }
urza-info = { path = "../urza-info" }
urza-rng = { path = "../urza-rng" }
urza-value = { path = "../urza-value" }
